### ISSUE TITLE
swizzle applicationDidFinishLaunching using mach_inject

### ISSUE THREAD

**Issue by atomikpanda** [rentzsch/mach_inject#10]
I am able to swizzle a method like when  a button is clicked but I can't swizzle a method like  `applicationDidFinishLaunching` that runs before mach_inject injects the code. Is there a solution to this where I can run code inside the targeted app at injection time?

**Comment by rentzsch** [comment]
If you need to inject code early on then you'll want to use something like `DYLD_INSERT_LIBRARIES` instead of mach_inject.

**Comment by atomikpanda** [comment]
Thanks for your quick response. Do you know of any way to use `DYLD_INSERT_LIBRARIES` without having to run the binary manually? @rentzsch

**Comment by rentzsch** [comment]
Sorry, I haven't needed to do that myself.

**Comment by marpaia** [comment]
@s0ulp1xel check out setting environment variables via /etc/launchd.conf and/or environment.plist
