### ISSUE TITLE
[QUESTION] mach_inject without root permissions like Dropbox

### ISSUE THREAD

**Issue by JoseExposito** [rentzsch/mach_inject#2]
Hi!

I'm making a Finder "plugin" for Ubuntu One:
https://github.com/JoseExposito/U1-Finder-Plugin

Currently I'm using a SIMBL like loader making my plugin as a scripting addition:
https://github.com/JoseExposito/U1-Finder-Plugin/blob/master/U1%20Finder%20Injector/U1FinderInjector.m

But I don't like this method because I need to restart the Finder to allow to inject the plugin.

I see like some applications (like Dropbox) are able to use mach_inject without as for the admin password and my question is... How to do that??

Than you very much for the support in avance!

**Comment by rentzsch** [comment]
I don't know exactly how Dropbox does theirs, but I believe if you're code-signed on 10.6 and later you're free to call task_for_pid().

**Comment by JoseExposito** [comment]
Hi rentzsch,

Thank you very much for your rapid answer. I'll try to sign the code

Greetings and thanks again!!

**Comment by JoseExposito** [comment]
Hi again Rentzsch,

Finally I have signed my code (with a self signed certificate) following these links:

```
http://os-tres.net/blog/2010/02/17/mac-os-x-and-task-for-pid-mach-call/
http://haxpath.squarespace.com/imported-20100930232226/2010/8/12/debugging-on-snow-leopard-getting-task_for_pid-to-work.html
```

And I have the same problem:

```
Could not access task for pid 936. You probably need to add user to procmod group
mach_inject failing.. (ipc/send) invalid destination port
```

Any sugestion?
Thank you!!

**Comment by rentzsch** [comment]
I'm not sure, but you may need to sign it with an Apple-Signed Cert ($99/year). For now you can just add $USER to the procmod group like the error message says. That was introduced on 10.4 IIRC.

**Comment by JoseExposito** [comment]
Hi,

I can confirm that it is necessary to use a Apple signed certificate. In addition is very important to add this to your plist:

```
<key>SecTaskAccess</key>
<array>
    <string>allowed</string>
</array>
```

Thank you very much Rentzsch!!

**Comment by erwanb** [comment]
@JoseExposito the new Right Way™ to execute code as root is to install a privileged helper tools (require admin password during install). Then you can execute your helper tool as root without password.
See SMJobBless to install a helper tool: http://developer.apple.com/library/mac/#documentation/ServiceManagement/Reference/ServiceManagement_header_reference/Reference/reference.html#//apple_ref/doc/uid/TP40012447

**Comment by JoseExposito** [comment]
Hi @erwanb 
Thank you very much, I'll try to implement this method, but looks more complicate than simply sign the code

Thanks for the support!!!

**Comment by JoseExposito** [comment]
Unfortunately, only with code sign method, the admin password is asked to the user after reboot... 

@erwanb Do you know if with SMJobBless this occurs??

**Comment by erwanb** [comment]
@JoseExposito Once a helper tool has been installed in launchd (a helper tool is treated as a daemon), you never have to give an admin password, except for installing a new version or uninstalling it.

**Comment by JoseExposito** [comment]
@erwanb Thank you so much!! I'll try to implement this method this weekend. I'll post the code once it is finished

Thank again to the two for the help!

**Comment by rcontractor** [comment]
Did SMJobBless work for you? How did you integrate it with mach_inject?

**Comment by JoseExposito** [comment]
@rcontractor No, I have not been able to make it work successfully. You can try to check this examples:
https://github.com/jgfoster/SMJobBless
https://github.com/atnan/SMJobBlessXPC

I have not found the way to make work it.

**Comment by erwanb** [comment]
@rcontractor @JoseExposito Hey guys, I've put together a sample project that inject code into the finder using SMJobBless. You can find it here: https://github.com/erwanb/MachInjectSample.git
Hope that helps

**Comment by rentzsch** [comment]
Nice work, @erwanb. The current sample code in the mainline is old and crusty. How about you copy your sample into the mainline and toss me a pull request? I'll add you as a collaborator so you can still fix bugs or whatnot.

**Comment by erwanb** [comment]
@rentzsch Great, I'll do that.

**Comment by sdsykes** [comment]
Just for completeness...

I was actually wondering how Dropbox do it as nothing likely is present in /Library/LaunchDaemons (which is what you end up with if you use the SMJobBless technique).

The answer is they place setuid root executables in /Library/DropBoxHelperTools
Like so:

```
$ ls -lR /Library/DropboxHelperTools/
total 2984
-r-s--x--x  1 root  wheel  1523840 Mar 13 19:43 DropboxHelperInstaller
drwxr-xr-x  9 root  wheel      306 Mar 13 19:43 Dropbox_u501

/Library/DropboxHelperTools//Dropbox_u501:
total 504
drwxr-xr-x  4 root  wheel     136 Mar 13 19:43 DropboxBundle.bundle
-r-s--x--x  1 root  wheel  138856 Mar 13 19:43 FinderLoadBundle
-r-s--x--x  1 root  wheel  116668 Mar 13 19:43 dbfseventsd
drwxr-xr-x  4 root  wheel     136 Mar 13 19:43 mach_inject_bundle_stub.bundle
...
```

@erwanb's technique is rather nicer.

**Comment by jamiefoster** [comment]
@sdsykes @erwanb @rentzsch Do any of these methos make it possible to inject a bundle (or dylib) automatically when the process starts? Just want to make sure that I can modify Finder right when it starts (before it executes any of its code) and want to do this in an automatic way (start with the OS and inject whenever I see that Finder is executed). Is this possible?

**Comment by rodionovd** [comment]
@jamiefoster 

Well, I'm not sure there's any «automatic» way of doing so. But you can create your own launch agent (hint: use [«RunAtLoad»](http://launchd.info)) that will be notified when Finder starts.

Also, are you aware of [Finder Sync extensions](https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/ExtensibilityPG/Finder.html)? That's what Dropbox uses nowadays.

**Comment by jamiefoster** [comment]
@rodionovd Thank you for the reply!
So RunAtLoad will make sure that my launch agent runs when OSX starts.

Let's say I want to hook when a specific process is executed. How should I program my agent so that it gets notified when that process is executed, injects my dylib/bundle into that process and the resumes execution (calls main() )?

**Comment by rodionovd** [comment]
@jamiefoster Well, it depends on whether you (1) want to be notified when a _GUI application_ launches or (2) it's about ANY process.  

In the former case you should just register to notifications like `NSWorkspaceWillLaunchApplicationNotification` via Cocoa APIs.  

> I've done something similar for one of my apps: https://github.com/rodionovd/Locatr/blob/master/Locatr/LRInjector.m#L44  

If it's the latter — I have some bad news for you: there isn't any API that enables you to be notified about an arbitrary process startup. Even «System Monitor» app uses a timer to update it's process list.  

> And even fetching the list of processes is tricky. Take a look at `GetNextProcess()` or `LSCopyRunningApplicationsArray()` — https://github.com/rodionovd/RDProcess/blob/master/RDProcess.m#L174

I'm also not really sure about your idea of injecting code _before_ the process actually starts (i.e. before it's `main()`). I might be wrong, but I don't think it's possible to do, so just inject your code like if your target have been running for a while.
